# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://docteurelsavancaster.netlify.app"
languageCode = "fr"

theme = "congo"
defaultContentLanguage = "fr"

enableRobotsTXT = true
paginate = 15
summaryLength = 0

googleAnalytics = "309562473"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
