# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"

baseURL = "https://www.docteurelsavancaster.com/"
defaultContentLanguage = "fr"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

googleAnalytics = "G-N11WQL5DS3"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
