languageCode = "fr"
languageName = "French"
displayName = ":flag-fr:"
isoCode = "fr"
weight = 1
rtl = false

title = "Dr Elsa Vancaster"
# logo = "img/logo.jpg"
description = "Site internet du docteur Elsa Vancaster, médecin généraliste à Incourt (Piétrebais)"
copyright = "&copy; Dr Elsa Vancaster"

dateFormat = "2 January 2006"

[author]
  name = "Dr Elsa Vancaster"
  image = "img/docteur-elsa-vancaster.jpeg"
