languageCode = "fr-BE"
languageName = "French"
languageDirection = "ltr"
weight = 1

title = "Dr Elsa Vancaster"
# copyright = "Dr Elsa Vancaster"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["samples"]
  description = "Site internet du docteur Elsa Vancaster, médecin généraliste à Incourt (Piétrebais)"

[author]
  name = "Dr Elsa Vancaster"
  image = "img/docteur-elsa-vancaster.jpeg"
